run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - exportloopref
    - gocheckcompilerdirectives
    # FIXME: for some reason this errors on windows
    # - gofmt
    # - goimports
    - misspell
    - nilerr
    - unused
linters-settings:
  errcheck:
    # exclude the following functions since we don't generally
    # need to be concerned with the returned errors
    exclude-functions:
      - encoding/binary.Read
      - (*os.File).Seek
      - (*bufio.Writer).WriteString
      - (*github.com/spf13/pflag.FlagSet).Set
      - (*github.com/jmorganca/ollama/llm.readSeekOffset).Seek
